CREATE TABLE IF NOT EXISTS `fosreviews_review` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ACTIVE` TINYINT(11) NOT NULL,
  `USER_ID` INT(11) NOT NULL,
  `PRODUCT_ID` INT(11) NOT NULL,
  `PUBLICATION_DATE` INT(11) NOT NULL,
  `COMMENT` TEXT NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `fosreviews_photo` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `REVIEW_ID` INT(11) NOT NULL,
  `FILE_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `fosreviews_rating` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `REVIEW_ID` INT(11) NOT NULL,
  `PRODUCT_ID` INT(11) NOT NULL,
  `RATING` INT(11) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `fosreviews_like` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(11) NOT NULL,
  `REVIEW_ID` INT(11) NOT NULL,
  `LIKED` TINYINT(11) NOT NULL,
  PRIMARY KEY (`ID`)
);
